import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gradient-to-r from-[#882e27] via-[#6d869a] to-[#231641] text-white pt-10 pb-40">
        <div className="lg:w-[60%] w-[90%] mx-auto text-center">
          <h1 className="lg:text-5xl text-3xl font-semibold mb-3">
            Every tool you need to work with PDFs in one place
          </h1>
          <p className="lg:text-2xl text-xl leading-6">
            Every tool you need to use PDFs, at your fingertips. All are 100%
            FREE and easy to use! Merge, split, compress, convert, rotate,
            unlock and watermark PDFs with just a few clicks.
          </p>
        </div>
      </div>
      <div className="flex flex-wrap w-[90%] mx-auto z-10">
        <Link
          href={"/pdf-to-word"}
          className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 -mt-16 hover:bg-gray-100"
        >
          <h1 className="text-2xl mb-2 font-semibold">PDF to Word</h1>
          <p className="text-[#626870] text-sm">
            Combine PDFs in the order you want with the easiest PDF merger
            available
          </p>
        </Link>
        <Link href={'/pdf-to-powerpoint'} className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 md:-mt-16 hover:bg-gray-100">
          <h1 className="text-2xl mb-2 font-semibold">PDF to Powerpoint</h1>
          <p className="text-[#626870] text-sm">
            Combine PDFs in the order you want with the easiest PDF merger
            available
          </p>
        </Link>
        <Link href={'/pdf-to-excel'} className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 md:-mt-16 hover:bg-gray-100">
          <h1 className="text-2xl mb-2 font-semibold">PDF to Excel</h1>
          <p className="text-[#626870] text-sm">
            Combine PDFs in the order you want with the easiest PDF merger
            available
          </p>
        </Link>
        <Link href={'/word-to-pdf'} className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 lg:-mt-16 hover:bg-gray-100">
          <h1 className="text-2xl mb-2 font-semibold">Word to PDF</h1>
          <p className="text-[#626870] text-sm">
            Easily convert your PDF files into easy to edit DOC and DOCX
            documents. The converted WORD document is almost 100% accurate.
          </p>
        </Link>
        <Link href={'/powerpoint-to-pdf'} className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 lg:-mt-16 hover:bg-gray-100">
          <h1 className="text-2xl mb-2 font-semibold">Powerpoint to PDF</h1>
          <p className="text-[#626870] text-sm">
            Combine PDFs in the order you want with the easiest PDF merger
            available
          </p>
        </Link>
        <Link href={'/excel-to-pdf'} className="lg:w-1/6 md:w-1/3 w-1/1 shadow-md bg-white px-7 py-7 lg:-mt-16 hover:bg-gray-100">
          <h1 className="text-2xl mb-2 font-semibold">Excel to PDF</h1>
          <p className="text-[#626870] text-sm">
            Combine PDFs in the order you want with the easiest PDF merger
            available
          </p>
        </Link>
      </div>
    </>
  );
}
